---
title: DevLog de um entusiasta de tecnologia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: docg1701
description: Um blog para documentar minha jornada de aprendizado em desenvolvimento,  tecnologia
  e outros devaneios.
url: https://docg1701.github.io
github_username: docg1701
theme: klise
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
