---
title: I'm not a dev, but this is my devlog.
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: docg1701
description: These are some notes for myself and others interested in context-engineering,
  AI research and LLM assisted development.
url: https://docg1701.github.io
github_username: docg1701
theme: klise
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
